In [ ]:
import pandas as pd

In [12]:
df = pd.read_excel('../data/Sales Jul.xlsx', sheet_name='Jul25 - Oct25')

In [13]:
df.head()

,Material,Billing Doc.,Item,SALES OFFICE CODE,EXT MAT GROUP,MatGroup3,Star Rating,Segment,Star Rating.1,SBU,Billing Date,Customer,Billing Quantity ODU,Billing Quantity IDU,Tonnage,Dealer Name,Segment.1
0,RKU35UV16W,2529005146,NaN,BLR,RA-ODU,RA,NaN,Inv,5 Star,RA,2025-07-04,Aircare Technologies India Pvt Ltd,6.0,NaN,NaN,Aircare Technologies India Pvt Ltd,SSD
1,RL35UV16W1,2529005167,NaN,BLR,RA-ODU,RA,NaN,Non Inv,3 Star,RA,2025-07-04,Aircare Technologies India Pvt Ltd,10.0,NaN,NaN,Aircare Technologies India Pvt Ltd,SSD
2,JTKJ50UV16VA,2529005167,NaN,BLR,RA-IDU,RA,NaN,Inv,5 Star,RA,2025-07-04,Aircare Technologies India Pvt Ltd,NaN,3.0,NaN,Aircare Technologies India Pvt Ltd,SSD
3,RKJ50UV16V,2529005167,NaN,BLR,RA-ODU,RA,NaN,Inv,3 Star,RA,2025-07-04,Aircare Technologies India Pvt Ltd,3.0,NaN,NaN,Aircare Technologies India Pvt Ltd,SSD
4,FTL28UV16W1,2529005175,NaN,BLR,RA-IDU,RA,NaN,Non Inv,3 Star,RA,2025-07-04,DAWNTECH ELECTRONICS PVT LTD,NaN,3.0,NaN,DAWNTECH ELECTRONICS PVT LTD,Dealer Billing

In [23]:
df_subset = df[['Material', 'SALES OFFICE CODE', 'Segment','Star Rating.1', 'Billing Date', 'Billing Quantity ODU','Billing Quantity IDU', 'Tonnage']]

In [24]:
df_subset.fillna(0, inplace=True)
df_subset = df_subset[df_subset['Billing Quantity ODU'] > 0]
df_subset.rename(columns={
    'Billing Date': 'Date', 
'Material': 'Item Code', 
'SALES OFFICE CODE': 'Branch', 'Star Rating.1': 'Star Rating', 'Billing Quantity ODU': 'Quantity', 'Tonnage': 'Tonnage'}, inplace=True)
df_subset['Date'] = pd.to_datetime(df_subset['Date'])
df_subset.drop(columns=['Billing Quantity IDU'], inplace=True)
df_subset

/var/folders/vg/pxkxmzld5s73d47lq0mx8hyr0000gn/T/ipykernel_66840/3087856399.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset.fillna(0, inplace=True)

          Item Code Branch  Segment Star Rating       Date  Quantity  Tonnage
0        RKU35UV16W    BLR      Inv      5 Star 2025-07-04       6.0      0.0
1        RL35UV16W1    BLR  Non Inv      3 Star 2025-07-04      10.0      0.0
3        RKJ50UV16V    BLR      Inv      3 Star 2025-07-04       3.0      0.0
5        RL28UV16W1    BLR  Non Inv      3 Star 2025-07-04       3.0      0.0
9        RL28UV16W1    BLR  Non Inv      3 Star 2025-07-04       3.0      0.0
...             ...    ...      ...         ...        ...       ...      ...
20744   RKM50UV16VA   SBD1      Inv      5 Star 2025-10-31       5.0      0.0
20746  RKL50UV16VAF   SBD1      Inv      3 Star 2025-10-31       3.0      0.0
20748  RKL50UV16VAF   SBD1      Inv      3 Star 2025-10-31       5.0      0.0
20750   RKM50UV16VA   SBD1      Inv      5 Star 2025-10-31       5.0      0.0
20752  RKL50UV16VAF   SBD1      Inv      3 Star 2025-10-31       5.0      0.0

[10237 rows x 7 columns]

In [25]:
df_subset.groupby(['Branch', df_subset['Date'].dt.to_period('M').dt.to_timestamp()])['Quantity'].sum()

Branch  Date
BLR     2025-07-01    2009.0
        2025-08-01    2506.0
        2025-09-01    3354.0
        2025-10-01    2135.0
COK     2025-07-01    3757.0
        2025-08-01    6190.0
        2025-09-01    6277.0
        2025-10-01    2388.0
MAA     2025-07-01    6455.0
        2025-08-01    8511.0
        2025-09-01    9155.0
        2025-10-01    7495.0
SBD     2025-07-01    2602.0
        2025-08-01    4655.0
        2025-09-01    5107.0
        2025-10-01    3897.0
SBD1    2025-07-01    2019.0
        2025-08-01    3004.0
        2025-09-01    4910.0
        2025-10-01    3252.0
Name: Quantity, dtype: float64