In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('../data/Sales Jul.xlsx', sheet_name='Jul25 - Oct25')

In [3]:
df.head()

,Material,Billing Doc.,Item,SALES OFFICE CODE,EXT MAT GROUP,MatGroup3,Star Rating,Segment,Star Rating.1,SBU,Billing Date,Customer,Billing Quantity ODU,Billing Quantity IDU,Tonnage,Dealer Name,Segment.1
0,RKU35UV16W,2529005146,NaN,BLR,RA-ODU,RA,NaN,Inv,5 Star,RA,2025-07-04,Aircare Technologies India Pvt Ltd,6.0,NaN,NaN,Aircare Technologies India Pvt Ltd,SSD
1,RL35UV16W1,2529005167,NaN,BLR,RA-ODU,RA,NaN,Non Inv,3 Star,RA,2025-07-04,Aircare Technologies India Pvt Ltd,10.0,NaN,NaN,Aircare Technologies India Pvt Ltd,SSD
2,JTKJ50UV16VA,2529005167,NaN,BLR,RA-IDU,RA,NaN,Inv,5 Star,RA,2025-07-04,Aircare Technologies India Pvt Ltd,NaN,3.0,NaN,Aircare Technologies India Pvt Ltd,SSD
3,RKJ50UV16V,2529005167,NaN,BLR,RA-ODU,RA,NaN,Inv,3 Star,RA,2025-07-04,Aircare Technologies India Pvt Ltd,3.0,NaN,NaN,Aircare Technologies India Pvt Ltd,SSD
4,FTL28UV16W1,2529005175,NaN,BLR,RA-IDU,RA,NaN,Non Inv,3 Star,RA,2025-07-04,DAWNTECH ELECTRONICS PVT LTD,NaN,3.0,NaN,DAWNTECH ELECTRONICS PVT LTD,Dealer Billing

In [15]:
df_subset = df[['Material', 'SALES OFFICE CODE', 'Segment','Star Rating.1', 'Billing Date', 'Billing Quantity ODU','Billing Quantity IDU', 'Tonnage']]

In [16]:
df_subset.fillna(0, inplace=True)
df_subset = df_subset[df_subset['Billing Quantity ODU'] > 0]
df_subset.rename(columns={
    'Billing Date': 'Date', 
'Material': 'Item Code', 
'SALES OFFICE CODE': 'Branch', 'Star Rating.1': 'Star Rating', 'Billing Quantity ODU': 'Quantity', 'Tonnage': 'Tonnage'}, inplace=True)
df_subset['Date'] = pd.to_datetime(df_subset['Date'])
df_subset.drop(columns=['Billing Quantity IDU'], inplace=True)
df_subset['Region'] = 'South'

C:\Users\sahil\AppData\Local\Temp\ipykernel_25444\577798192.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset.fillna(0, inplace=True)

In [17]:
df_subset

,Item Code,Branch,Segment,Star Rating,Date,Quantity,Tonnage,Region
0,RKU35UV16W,BLR,Inv,5 Star,2025-07-04,6.0,0.0,South
1,RL35UV16W1,BLR,Non Inv,3 Star,2025-07-04,10.0,0.0,South
3,RKJ50UV16V,BLR,Inv,3 Star,2025-07-04,3.0,0.0,South
5,RL28UV16W1,BLR,Non Inv,3 Star,2025-07-04,3.0,0.0,South
9,RL28UV16W1,BLR,Non Inv,3 Star,2025-07-04,3.0,0.0,South
...,...,...,...,...,...,...,...,...
20744,RKM50UV16VA,SBD1,Inv,5 Star,2025-10-31,5.0,0.0,South
20746,RKL50UV16VAF,SBD1,Inv,3 Star,2025-10-31,3.0,0.0,South
20748,RKL50UV16VAF,SBD1,Inv,3 Star,2025-10-31,5.0,0.0,South
20750,RKM50UV16VA,SBD1,Inv,5 Star,2025-10-31,5.0,0.0,South
20752,RKL50UV16VAF,SBD1,Inv,3 Star,2025-10-31,5.0,0.0,South

In [21]:
main_df = pd.read_csv('../data/merged_filter_ingestion.csv')
main_df['Date'] = pd.to_datetime(main_df['Date'])
main_df.drop(columns=['Unnamed: 0'], inplace=True)

In [22]:
merged_df = pd.concat([main_df, df_subset])

In [ ]:
merged_df.to_csv('../data/merged_filter_ingestion_latest.csv', index=False)

,Date,Item Code,Branch,Star Rating,Segment,Quantity,Tonnage,Region
0,2020-03-23,RKG35TV16W,COK,5 Star,Inv,2.0,1.0,South
1,2020-03-23,RKL35TV16X,COK,3 Star,Inv,2.0,1.0,South
2,2020-03-23,RL28TV16X2,COK,3 Star,Non Inv,2.0,0.8,South
3,2020-03-23,RL28TV16X2,COK,3 Star,Non Inv,10.0,0.8,South
4,2020-03-23,RLG35TV16W1,COK,3 Star,Non Inv,10.0,1.0,South
...,...,...,...,...,...,...,...,...
20744,2025-10-31,RKM50UV16VA,SBD1,5 Star,Inv,5.0,0.0,South
20746,2025-10-31,RKL50UV16VAF,SBD1,3 Star,Inv,3.0,0.0,South
20748,2025-10-31,RKL50UV16VAF,SBD1,3 Star,Inv,5.0,0.0,South
20750,2025-10-31,RKM50UV16VA,SBD1,5 Star,Inv,5.0,0.0,South
20752,2025-10-31,RKL50UV16VAF,SBD1,3 Star,Inv,5.0,0.0,South